setup:
  root_dir: '/Users/apeck/Desktop/diffuse/processing/cxidb_128/temp'
  pdb_path: '../tests/pdbs/6o2h_clean.pdb'
  exp_map: '/Users/apeck/Desktop/diffuse/processing/cxidb_128/models/exp_rasu.npy'
  hsampling: [-22.46153846153846, 22.46153846153846, 13]
  ksampling: [-27.454545454545453, 27.454545454545453, 11]
  lsampling: [-0.45454545454545453, 30.454545454545453, 11]
  res_limit: 1.25
  batch_size: 5000
  parallelize: multiprocess
  implementation: torch

RigidBodyTranslations:
  sigmas_min: 0.1
  sigmas_max: 0.9
  n_search: 9
  expand_friedel: False